version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: circuitverse_development
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${CURRENT_UID}
        - GROUP_ID=${CURRENT_GID}
    entrypoint: ./bin/docker_run
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CIRCUITVERSE_USE_SOLR: "false"
      DOCKER_ENVIRONMENT: "true"
      RAILS_ENV: "development"
      NODE_ENV: "development"
    volumes:
      - .:/circuitverse:rw
      - ./config/database.docker.yml:/circuitverse/config/database.yml:rw
      - ruby_bundle:/usr/local/bundle:rw
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
      - redis


volumes:
  ruby_bundle: