class Assignment < ApplicationRecord
  def notify_recipient: () -> void

  def send_new_assignment_mail: () -> void

  def send_update_mail: () -> void

  def set_deadline_job: () -> void

  def clean_restricted_elements: () -> ActiveRecord::Type::Json

  def graded?: () -> ActiveRecord::Type::Boolean

  def elements_restricted?: () -> ActiveRecord::Type::Boolean

  def lti_integrated?: () -> ActiveRecord::Type::Boolean

  def project_order: () -> Array[ProjectDecorator]

  def check_reopening_status: () -> ActiveRecord::Type::Boolean
end
